### PR TITLE
added typescript definition types

### PR DESCRIPTION
**Pull request by neophyt3**

### CODE REVIEW

**Comment by erfanium** [comment]
@hemerajs
May you check this?

**Comment by StarpTech** [comment]
Thanks for the PR! Please add a test with https://github.com/SamVerschueren/tsd for the types. Here is an example https://github.com/StarpTech/next-localization/blob/master/types/index.test-d.ts

**Comment by erfanium** [comment]
@StarpTech 
I added a tsd test in #17

**Comment by neophyt3** [comment]
#18  looks good to me
@StarpTech  pls go ahead with #18

**Comment by StarpTech** [comment]
Released with 3.1.0.

**Pull request closed without merging**
