### PR TITLE
Update project status

### PR DESCRIPTION
**Pull request by lboquillon**
Hello,
Reading some closed PR like this one: https://github.com/hemerajs/fastify-graceful-shutdown/pull/37 could be seen that the project is not accepting new features and it is recommended to use [close-with-grace](https://github.com/mcollina/close-with-grace). So I created this PR to update the status so future users consider using a different alternative. This might be beneficial.

### CODE REVIEW

**Comment by StarpTech** [comment]
Hi, I'm not sure why you got this impression. The last release was 1 week ago https://github.com/hemerajs/fastify-graceful-shutdown/releases/tag/v4.0.1

**Comment by lboquillon** [comment]
@StarpTech I got the impression because of this comment: https://github.com/hemerajs/fastify-graceful-shutdown/pull/37#issuecomment-1305404919

**Comment by StarpTech** [comment]
It's 2 years old. The situation has changed.

**Comment by lboquillon** [comment]
@StarpTech I see, sorry for the misunderstanding.
So would you be open to bring back this topic https://github.com/hemerajs/fastify-graceful-shutdown/pull/37 it would also be interesting for us to have that feature or a similar mechanism. I can create a similar PR.

**Comment by StarpTech** [comment]
Please continue the discussion in the issue. As [stated](https://github.com/hemerajs/fastify-graceful-shutdown/issues/36#issuecomment-1646836923) here, I'm ok with logging a WARN rather than throw.

**Pull request closed without merging**
